### ISSUE TITLE
Random Error when loading recipe

### ISSUE THREAD

**Issue by deadspidervenom** [Fulmineo64/CompanionBats#7]
com.google.gson.JsonSyntaxException: Unknown item 'companion_bats:command_flute'
        at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
        at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe:233) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
        at net.minecraft.recipe.ShapedRecipe.getItemStack(ShapedRecipe:233) ~[?:?]
        at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe:254) ~[?:?]
        at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe:241) ~[?:?]
        at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:123) ~[?:?]
        at net.minecraft.recipe.RecipeManager.apply(RecipeManager:54) ~[?:?]
        at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
        at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
        at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]

**Comment by Fulmineo64** [comment]
Hi,
this issue should be solved in the latest version for 1.16 (1.13.4).

If it doesn't solve your problem or if you're playing on 1.17 please let me know!
Thank you.
